# Generated by Django 3.2.6 on 2021-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='body',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
