# Generated by Django 3.2.6 on 2021-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_alter_forum_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='languages',
            field=models.CharField(default='', max_length=50),
        ),
    ]
