# Generated by Django 3.2.6 on 2021-10-18 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title_1', models.CharField(default='', max_length=200)),
                ('work_title_2', models.CharField(default='', max_length=200)),
                ('work_title_3', models.CharField(default='', max_length=200)),
                ('work_title_4', models.CharField(default='', max_length=200)),
                ('work_title_5', models.CharField(default='', max_length=200)),
                ('work_val_1', models.IntegerField(default=0)),
                ('work_val_2', models.IntegerField(default=0)),
                ('work_val_3', models.IntegerField(default=0)),
                ('work_val_4', models.IntegerField(default=0)),
                ('work_val_5', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default='')),
                ('github', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('facebook', models.URLField(default='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtar', models.ImageField(default='default.png', upload_to='avtar/')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=200)),
                ('tag', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
