# Generated by Django 3.2.6 on 2021-08-27 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='login',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='login',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='login',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title_1', models.CharField(default='', max_length=200)),
                ('work_title_2', models.CharField(default='', max_length=200)),
                ('work_title_3', models.CharField(default='', max_length=200)),
                ('work_title_4', models.CharField(default='', max_length=200)),
                ('work_title_5', models.CharField(default='', max_length=200)),
                ('work_val_1', models.IntegerField(default='')),
                ('work_val_2', models.IntegerField(default='')),
                ('work_val_3', models.IntegerField(default='')),
                ('work_val_4', models.IntegerField(default='')),
                ('work_val_5', models.IntegerField(default='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default='')),
                ('github', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('facebook', models.URLField(default='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
