# Generated by Django 3.2.6 on 2021-08-27 06:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20210827_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUrls',
            new_name='UserUrl',
        ),
    ]
