# Generated by Django 3.2.6 on 2021-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_userurls_userurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwork',
            name='work_val_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='work_val_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='work_val_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='work_val_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='work_val_5',
            field=models.IntegerField(default=0),
        ),
    ]
