# Generated by Django 3.2.6 on 2021-09-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_login_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='avtar',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
