# Generated by Django 3.2.6 on 2021-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_login_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='avtar',
            field=models.ImageField(default='login.png', upload_to='avtar/'),
        ),
    ]
