# Generated by Django 3.2.6 on 2021-10-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_login_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='avtar',
            field=models.ImageField(default='default.png', upload_to='avtar/'),
        ),
    ]
