# Generated by Django 3.2.6 on 2021-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('fullname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=100)),
                ('query', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
